### ISSUE TITLE
Issue using compile_static template tag

### ISSUE THREAD

**Issue by vCra** [andreyfedoseev/django-static-precompiler#116]
Hi, 
I was trying to run a build yesterday,
I got the following error 

```
18:32:03 Traceback (most recent call last):
18:32:03   File "/var/lib/jenkins/workspace/TILE/env/lib/python3.4/site-packages/django/template/backends/django.py", line 121, in get_package_libraries
18:32:03     module = import_module(entry[1])
18:32:03   File "/var/lib/jenkins/workspace/TILE/env/lib/python3.4/importlib/__init__.py", line 109, in import_module
18:32:03     return _bootstrap._gcd_import(name[level:], package, level)
18:32:03   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
18:32:03   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
18:32:03   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
18:32:03   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
18:32:03   File "<frozen importlib._bootstrap>", line 1129, in _exec
18:32:03   File "<frozen importlib._bootstrap>", line 1471, in exec_module
18:32:03   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
18:32:03   File "/var/lib/jenkins/workspace/TILE/env/lib/python3.4/site-packages/static_precompiler/templatetags/compile_static.py", line 7, in <module>
18:32:03     from .. import caching, registry, settings, utils
18:32:03   File "/var/lib/jenkins/workspace/TILE/env/lib/python3.4/site-packages/static_precompiler/registry.py", line 7, in <module>
18:32:03     from typing import *  # noqa
18:32:03 ImportError: No module named 'typing'
18:32:03 
18:32:03 During handling of the above exception, another exception occurred:
18:32:03 
18:32:03 Traceback (most recent call last):
18:32:03   File "/var/lib/jenkins/workspace/TILE/env/lib/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
18:32:03     response = get_response(request)
18:32:03   File "/var/lib/jenkins/workspace/TILE/env/lib/python3.4/site-packages/django/utils/deprecation.py", line 95, in __call__
18:32:03     response = self.get_response(request)
18:32:03   File "/var/lib/jenkins/workspace/TILE/env/lib/python3.4/site-packages/django/core/handlers/exception.py", line 37, in inner
18:32:03     response = response_for_exception(request, exc)
18:32:03   File "/var/lib/jenkins/workspace/TILE/env/lib/python3.4/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
18:32:03     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
18:32:03   File "/var/lib/jenkins/workspace/TILE/env/lib/python3.4/site-packages/django/core/handlers/exception.py", line 126, in handle_uncaught_exception
18:32:03     return callback(request, **param_dict)
18:32:03   File "/var/lib/jenkins/workspace/TILE/django_tile/urls.py", line 39, in handler500
18:32:03     t = loader.get_template('500.html')
18:32:03   File "/var/lib/jenkins/workspace/TILE/env/lib/python3.4/site-packages/django/template/loader.py", line 12, in get_template
18:32:03     engines = _engine_list(using)
18:32:03   File "/var/lib/jenkins/workspace/TILE/env/lib/python3.4/site-packages/django/template/loader.py", line 66, in _engine_list
18:32:03     return engines.all() if using is None else [engines[using]]
18:32:03   File "/var/lib/jenkins/workspace/TILE/env/lib/python3.4/site-packages/django/template/utils.py", line 88, in all
18:32:03     return [self[alias] for alias in self]
18:32:03   File "/var/lib/jenkins/workspace/TILE/env/lib/python3.4/site-packages/django/template/utils.py", line 88, in <listcomp>
18:32:03     return [self[alias] for alias in self]
18:32:03   File "/var/lib/jenkins/workspace/TILE/env/lib/python3.4/site-packages/django/template/utils.py", line 79, in __getitem__
18:32:03     engine = engine_cls(params)
18:32:03   File "/var/lib/jenkins/workspace/TILE/env/lib/python3.4/site-packages/django/template/backends/django.py", line 25, in __init__
18:32:03     options['libraries'] = self.get_templatetag_libraries(libraries)
18:32:03   File "/var/lib/jenkins/workspace/TILE/env/lib/python3.4/site-packages/django/template/backends/django.py", line 43, in get_templatetag_libraries
18:32:03     libraries = get_installed_libraries()
18:32:03   File "/var/lib/jenkins/workspace/TILE/env/lib/python3.4/site-packages/django/template/backends/django.py", line 108, in get_installed_libraries
18:32:03     for name in get_package_libraries(pkg):
18:32:03   File "/var/lib/jenkins/workspace/TILE/env/lib/python3.4/site-packages/django/template/backends/django.py", line 125, in get_package_libraries
18:32:03     "trying to load '%s': %s" % (entry[1], e)
18:32:03 django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'static_precompiler.templatetags.compile_static': No module named 'typing'
18:32:03 
```

I guess it is because I don't have "typing" installed - It is included in python 3.5 and above as part of stdlib, but on python 3.4 it isn't. Are you able to add typing in the setup.py for python versions < 3.4, or (less preferably) remove support for these older versions?

**Comment by andreyfedoseev** [comment]
Thank you for reporting this. I updated `setup.py` to install `typing` for python 3.4 and below (it was being installed on Python 2 already). This is fixed in version 1.8.1 which I just uploaded to PyPI.

I'm closing this, feel free to re-open if there're other problems with Python 3.4
