### ISSUE TITLE
Manage.py compilestatic:  Unable to scan directory?  (S3-hosted static files)

### ISSUE THREAD

**Issue by lupinia** [andreyfedoseev/django-static-precompiler#67]
Hi!  I'm trying to set this up on a Django 1.8 site, where all my media and static files are stored on S3.  So, I set STATIC_PRECOMPILER_DISABLE_AUTO_COMPILE, and tried to run compilestatic.  However, it gives me a "TypeError: coercing to Unicode: need string or buffer, NoneType found" exception in its scan/directory walk code.  Stack trace is below:  

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 660, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/site-packages/static_precompiler/management/commands/compilestatic.py", line 55, in handle_noargs
    for dirname, dirnames, filenames in os.walk(scanned_dir):
  File "/usr/lib64/python2.7/os.py", line 278, in walk
    names = listdir(top)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

And here's the relevant sections from my Django settings.  

``` python
DEFAULT_FILE_STORAGE = 's3_folder_storage.s3.DefaultStorage'
STATICFILES_STORAGE = 's3_folder_storage.s3.StaticStorage'
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'static_precompiler.finders.StaticPrecompilerFinder',
)
STATICFILES_DIRS = (os.path.abspath(os.path.join(BASE_DIR,'static/')),)

#   static_precompiler
STATIC_PRECOMPILER_DISABLE_AUTO_COMPILE = True
STATIC_PRECOMPILER_COMPILERS = ( ('static_precompiler.compilers.SCSS', {"executable": "/usr/local/bin/sassc", "compass_enabled": False}), )
STATIC_PRECOMPILER_ROOT = os.path.abspath(os.path.join(BASE_DIR,'static/'))
STATIC_PRECOMPILER_OUTPUT_DIR = 'css'
```

**Comment by lupinia** [comment]
Is this ever going to be fixed?  Or acknowledged in any way?

**Comment by andreyfedoseev** [comment]
@lupinia Could you try it again with the latest version of `static_precompiler`? It seems that the problem was caused by empty `STATIC_ROOT` setting. This case is properly handled in recent versions.
